export default [
    {
        "ba_long_name": "PT PERTAMINA EP",
        "ba_type": "BADAN USAHA",
        "area_id": "PERTAMINA EP",
        "area_type": "WILAYAH KERJA",
        "field_name": "BUNYU",
        "well_name": "BN-17",
        "uwi": "-",
        "title": "PVT ANALYSIS OF RESERVOIR FLUID",
        "creator_name": "LEMIGAS",
        "create_date": "",
        "media_type": "KERTAS",
        "document_type": "LAPORAN SUMUR",
        "item_category": "PENGUJIAN SUMUR",
        "item_sub_category": "ANALISA PVT",
        "page_count": "16",
        "remark": "LAPORAN BERISI 2 LAMPIRAN:1. SEISMIC CORRECTION SHEET, 2. SONIC CALIBRATION SHEET",
        "data_store_name": "PERTAMINA UPSTREAM DATA CENTER",
        "data_store_type": "SHELF",
        "source": "PT PERTAMINA EP",
        "qc_status": "TERVERIFIKASI OLEH SKK MIGAS",
        "checked_by_ba_id": "314583756281421"
    },
    {
        "ba_long_name": "PT PERTAMINA EP",
        "ba_type": "BADAN USAHA",
        "area_id": "PERTAMINA EP",
        "area_type": "WILAYAH KERJA",
        "field_name": "BUNYU",
        "well_name": "BN-18",
        "uwi": "-",
        "title": "PVT ANALYSIS OF RESERVOIR FLUID",
        "creator_name": "LEMIGAS",
        "create_date": "",
        "media_type": "KERTAS",
        "document_type": "LAPORAN SUMUR",
        "item_category": "PENGUJIAN SUMUR",
        "item_sub_category": "ANALISA PVT",
        "page_count": "20",
        "remark": "LAPORAN BERISI 2 LAMPIRAN:1. SEISMIC CORRECTION SHEET, 2. SONIC CALIBRATION SHEET",
        "data_store_name": "PERTAMINA UPSTREAM DATA CENTER",
        "data_store_type": "SHELF",
        "source": "PT PERTAMINA EP",
        "qc_status": "TERVERIFIKASI OLEH SKK MIGAS",
        "checked_by_ba_id": "3143591832196432"
    },
    {
        "ba_long_name": "PT PERTAMINA EP",
        "ba_type": "BADAN USAHA",
        "area_id": "PERTAMINA EP",
        "area_type": "WILAYAH KERJA",
        "field_name": "BUNYU",
        "well_name": "BN-19",
        "uwi": "-",
        "title": "PVT ANALYSIS OF RESERVOIR FLUID",
        "creator_name": "LEMIGAS",
        "create_date": "",
        "media_type": "KERTAS",
        "document_type": "LAPORAN SUMUR",
        "item_category": "PENGUJIAN SUMUR",
        "item_sub_category": "ANALISA PVT",
        "page_count": "11",
        "remark": "LAPORAN BERISI 2 LAMPIRAN:1. SEISMIC CORRECTION SHEET, 2. SONIC CALIBRATION SHEET",
        "data_store_name": "PERTAMINA UPSTREAM DATA CENTER",
        "data_store_type": "SHELF",
        "source": "PT PERTAMINA EP",
        "qc_status": "TERVERIFIKASI OLEH SKK MIGAS",
        "checked_by_ba_id": "314583756209278"
    }
]