import Head from 'next/head'
import Image from 'next/image'
import Buttons, { Buttons_Sidebar } from '../components/buttons'
import Bibliography from '../public/icons/bibliography.svg'
import Info from '../public/icons/info.svg'
import Maps from '../public/icons/maps.svg'
import Outcrop from '../public/icons/outcrop.svg'
import Project_file from '../public/icons/project_file.svg'
import Seismic from '../public/icons/seismic.svg'
import Technical_report from '../public/icons/technical_report.svg'
import Well from '../public/icons/well.svg'
import Well_sample_core from '../public/icons/well_sample_core.svg'
import Arrow from '../public/icons/arrow_notrail.svg'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="flex flex-col h-screen text-[14.5px]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='border border-black h-[60px] flex-none'>
        Navbar
      </div>
      <div className='flex flex-col'>
        <div className='flex '>
          <div className='bg-side_bar w-[300px] px-3 py-2.5 border-t-0'>
            <div className='overflow-auto'>
              <div className='flex flex-col space-y-[1px] min-h-0 border border-black'>
                <Buttons_Sidebar path='' button_description='General information'>
                  <Info className='w-4' />
                </Buttons_Sidebar>
                <Buttons_Sidebar path='' button_description='Seismic data'>
                  <Seismic className='w-4' />
                </Buttons_Sidebar>
                <Buttons_Sidebar path='' button_description='Non-Seismic & Seismic Non Conventional Data'>
                  <Seismic className='w-4' />
                </Buttons_Sidebar>
                <Buttons_Sidebar path='' button_description='Well data'>
                  <Well className='w-4' />
                </Buttons_Sidebar>
                <Buttons_Sidebar path='' button_description='Well sample & Core'>
                  <Well_sample_core className='w-4' />
                </Buttons_Sidebar>
                <Buttons_Sidebar path='' button_description='Outcrop'>
                  <Outcrop className='w-4' />
                </Buttons_Sidebar>
                <Buttons_Sidebar path='' button_description='Technical report'>
                  <Technical_report className='w-4' />
                </Buttons_Sidebar>
                <Buttons_Sidebar path='' button_description='Maps & Technical'>
                  <Maps className='w-4' />
                </Buttons_Sidebar>
                <Buttons_Sidebar path='' button_description='Project file'>
                  <Project_file className='w-4' />
                </Buttons_Sidebar>
                <Buttons_Sidebar path='' button_description='Bibliography'>
                  <Bibliography className='w-4' />
                </Buttons_Sidebar>
              </div>
              <div className='bottom-0 left-0 w-full bg-side_bar'>
                <button className='flex space-x-2 hover:bg-gray-200 w-full px-6 py-3'>
                  <div className='flex -space-x-1.5'>
                    <Arrow className='w-3 rotate-180' />
                    <Arrow className='w-3 rotate-180' />
                  </div>
                  <label>Collapse sidebar</label>
                </button>
              </div>
            </div>
          </div>
          <div className='flex flex-col space-y-3 justify-center items-center h-full w-full'>
            <Buttons path='/test' button_description='Choose file manually' />
            <Buttons path='/test' button_description='Make a new document' />
            <Buttons path='/test' button_description='View drafts' />
            <Buttons path='/test' button_description='Connect with database' />
            <Buttons path={'/anothertest'} button_description='CLICK THIS BUTTON TO VIEW THE COMPLETE DEMO PAGE' additional_styles='font-bold text-3xl' />
          </div>
        </div>
      </div>
    </div>
  )
}
